import { Alert, Badge, Button, Card, Grid, Group, List, SimpleGrid, Text, ThemeIcon, Timeline, Title } from '@mantine/core';
import { Activity, ArrowRight, CheckCircle2, CircleDashed, Clock3, Info, ShieldCheck, Wrench } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/PageHeader';

export type FeatureKey =
  | 'dynamic' | 'leases' | 'rotation' | 'risk' | 'transit' | 'crypto-operations'
  | 'certificates' | 'pki' | 'expiration' | 'environments' | 'dependencies'
  | 'events' | 'security-events' | 'cluster' | 'storage' | 'infrastructure-security'
  | 'namespaces' | 'preferences' | 'guide';

interface FeatureConfig {
  eyebrow: string; title: string; description: string; badge: string; notice?: string;
  metrics: Array<{ label: string; value: string; detail: string }>;
  capabilities: string[]; next: string[]; action?: { label: string; path: string };
}

const configs: Record<FeatureKey, FeatureConfig> = {
  dynamic: { eyebrow: 'Credential broker', title: '동적 자격 증명', description: '장기 비밀번호 대신 짧은 TTL의 일회성 자격 증명을 발급하고 만료 시 폐기하는 후속 엔진입니다.', badge: '로드맵', notice: 'v0.2.0에는 동적 계정 발급·갱신·폐기 API와 Connector 실행기가 없습니다. 이 화면은 목표 계약만 설명합니다.', metrics: [{ label: '활성 Lease', value: '—', detail: '엔진 미지원' }, { label: '오늘 발급', value: '—', detail: '엔진 미지원' }, { label: '자동 폐기', value: '—', detail: '스케줄러 미지원' }], capabilities: ['TTL·최대 TTL 계약 설계', '감사 이벤트 분류 설계', '정책 capability 확장 지점'], next: ['PostgreSQL connector', 'Dual credential rotation', '대상 연결 검증'], action: { label: '지원 API 확인', path: '/api-explorer' } },
  leases: { eyebrow: 'Lease center', title: '리스 관리', description: '토큰과 동적 자격 증명의 수명주기를 추적하고 즉시 갱신·폐기하는 후속 엔진입니다.', badge: '로드맵', notice: 'v0.2.0은 만료형 세션·API 토큰을 제공하지만 OpenBao Lease 엔진, renew와 bulk revoke는 지원하지 않습니다.', metrics: [{ label: '활성 Lease', value: '—', detail: 'Lease 엔진 미지원' }, { label: '1시간 내 만료', value: '—', detail: 'Lease 엔진 미지원' }, { label: '폐기 실패', value: '—', detail: 'Lease 엔진 미지원' }], capabilities: ['만료형 세션·API 토큰', '토큰 소유자와 만료 시각', '개별 토큰 폐기'], next: ['Lease renew·revoke', 'Application 기준 필터', '비정상 장기 Lease 탐지'], action: { label: '토큰 보기', path: '/access/tokens' } },
  rotation: { eyebrow: 'Rotation orchestrator', title: '회전 관리', description: '현재는 개인 키 회전과 KV 새 버전 생성을 제공하며 Connector 기반 대상 반영은 후속 범위입니다.', badge: '수동 회전 제공', notice: 'v0.2.0의 Secret 회전은 자동 회전 가능 필드를 난수화해 새 버전으로 저장합니다. DB·외부 API 반영, Health check와 rollback은 수행하지 않습니다.', metrics: [{ label: '예약 작업', value: '—', detail: '스케줄러 미지원' }, { label: '최근 성공률', value: '—', detail: '집계 API 미지원' }, { label: 'Connector 실패', value: '—', detail: 'Connector 미지원' }], capabilities: ['개인 키 버전 회전', 'KV 시크릿 새 버전 생성', '승인 설정과 수동 작업 연계'], next: ['Connector 플러그인', 'Dual credential', 'Health check rollback'], action: { label: '키 관리 열기', path: '/encryption/keys' } },
  risk: { eyebrow: 'Risk engine', title: '시크릿 위험 분석', description: '운영 경로, Owner·Application 부재와 고권한 필드 이름을 기준으로 위험 우선순위를 계산합니다.', badge: '기본 규칙', notice: 'v0.2.0 위험 점수는 저장 시 계산하는 기본 규칙입니다. 접근 행동 학습, 회전 경과일과 정책 최적화는 지원하지 않습니다.', metrics: [{ label: '심각', value: '—', detail: '실시간 집계 미지원' }, { label: '높음', value: '—', detail: '실시간 집계 미지원' }, { label: 'Owner 없음', value: '—', detail: '목록에서 개별 확인' }], capabilities: ['PRD·production 경로 가중치', 'Owner·Application 부재 가중치', 'root·admin·private 필드 가중치'], next: ['행동 분석', 'Policy optimizer', '위험 추세 비교'], action: { label: '시크릿 검토', path: '/secrets' } },
  transit: { eyebrow: 'Encryption as a service', title: 'Transit 암호화', description: '애플리케이션이 원본 암호화 키를 보지 않고 API로 암·복호화합니다.', badge: 'OpenBao API 제한 프리뷰', notice: 'v0.2.0은 AES-256-GCM 단건 encrypt/decrypt만 제한 제공합니다. 이 화면에는 사용량 집계 API가 연결되지 않습니다.', metrics: [{ label: '활성 키', value: '—', detail: '집계 미지원' }, { label: '오늘 암호화', value: '—', detail: '집계 미지원' }, { label: '오늘 복호화', value: '—', detail: '집계 미지원' }], capabilities: ['AES-256-GCM 암호화', '키 버전 포함 ciphertext', '/v1/transit encrypt/decrypt 제한 프로파일'], next: ['Batch operation', 'Rewrap', 'HMAC·sign/verify'], action: { label: 'API에서 실행', path: '/api-explorer' } },
  'crypto-operations': { eyebrow: 'Crypto operations', title: '암호화 작업', description: 'API 탐색기에서 Transit 암호화·복호화 요청을 확인합니다.', badge: 'API 안내', metrics: [{ label: '알고리즘', value: 'AES-256', detail: 'GCM 인증 암호화' }, { label: 'JSON 요청 상한', value: '2 MiB', detail: '전체 요청 본문' }, { label: '감사', value: '요청', detail: '평문 제외 메타데이터' }], capabilities: ['현재 세션 권한 사용', '키 버전 자동 선택', '요청 ID 추적'], next: ['전용 암호화 폼', 'Batch 암호화', '서명 작업'], action: { label: 'API에서 실행', path: '/api-explorer' } },
  certificates: { eyebrow: 'Certificate inventory', title: '인증서 현황', description: '내부 인증서의 발급자, 만료, 알고리즘과 연결 서비스를 중앙에서 파악하는 후속 영역입니다.', badge: '로드맵', notice: 'v0.2.0에는 인증서 저장·탐색·발급 API가 없습니다. 아래 항목은 후속 데이터 모델의 설계 범위입니다.', metrics: [{ label: '전체', value: '—', detail: 'Inventory 미지원' }, { label: '30일 내 만료', value: '—', detail: '탐색 미지원' }, { label: '폐기', value: '—', detail: 'CRL 미지원' }], capabilities: ['인증서 메타데이터 모델 설계', '환경·애플리케이션 연결 설계', '만료 임계값 설계'], next: ['Root/Intermediate CA', 'Issue·renew·revoke', 'CRL·OCSP'] },
  pki: { eyebrow: 'PKI control center', title: 'PKI·CA', description: 'Root와 Intermediate CA, 역할과 발급 정책을 관리하는 후속 영역입니다.', badge: '로드맵', notice: 'CA 개인키를 안전하게 운영하기 위한 HSM·복구 검증 전에는 발급 기능을 활성화하지 않습니다.', metrics: [{ label: 'Root CA', value: '—', detail: 'PKI 엔진 미지원' }, { label: 'Intermediate', value: '—', detail: 'PKI 엔진 미지원' }, { label: '발급 정책', value: '—', detail: 'PKI 엔진 미지원' }], capabilities: ['CA 계층 데이터 모델 설계', '역할 기반 접근 설계', '감사 이벤트 분류 설계'], next: ['CSR·Issue API', 'CRL·OCSP', '자동 갱신'] },
  expiration: { eyebrow: 'Renewal planner', title: '인증서 만료 관리', description: '30일·14일·7일 임계값으로 갱신 우선순위를 관리하는 후속 영역입니다.', badge: '로드맵', notice: 'v0.2.0에는 인증서 Inventory가 없어 실제 만료 수치를 계산하지 않습니다.', metrics: [{ label: '30일', value: '—', detail: '집계 미지원' }, { label: '14일', value: '—', detail: '집계 미지원' }, { label: '7일', value: '—', detail: '집계 미지원' }], capabilities: ['만료 임계값 설계', 'Owner 연결 설계', '알림 정책 모델 설계'], next: ['TLS discovery', 'Auto renewal', '담당자 Task'] },
  environments: { eyebrow: 'Environment isolation', title: '환경', description: 'DEV·STG·PRD의 시크릿 구조와 정책을 분리해 운영 경계를 명확히 합니다.', badge: '기본 제공', metrics: [{ label: 'DEV', value: '활성', detail: '개발 환경' }, { label: 'STG', value: '활성', detail: '검증 환경' }, { label: 'PRD', value: '보호', detail: '운영 승인 정책 권장' }], capabilities: ['시크릿 환경 메타데이터', '환경별 검색', 'PRD 위험 가중치'], next: ['Schema promote', '환경별 기본 정책', 'Drift detection'], action: { label: '애플리케이션 보기', path: '/applications' } },
  dependencies: { eyebrow: 'Impact graph', title: '의존성 그래프', description: '시크릿을 변경하기 전에 연결된 애플리케이션과 운영 영향도를 파악하는 후속 기능입니다.', badge: '로드맵', notice: 'v0.2.0은 Secret과 Application의 직접 연결 ID만 저장합니다. 의존성 그래프, Pod 탐색과 영향도 계산 API는 지원하지 않습니다.', metrics: [{ label: '연결', value: '—', detail: '그래프 집계 미지원' }, { label: 'Critical', value: '—', detail: '영향도 계산 미지원' }, { label: '미연결', value: '—', detail: '집계 API 미지원' }], capabilities: ['Application ID와 Secret 연결', '애플리케이션 중요도·환경 메타데이터', '확장 가능한 관계 모델'], next: ['React Flow 시각화', 'Kubernetes Pod 탐색', 'Rolling restart 권고'], action: { label: '앱 카탈로그', path: '/applications' } },
  events: { eyebrow: 'Event delivery', title: '이벤트', description: '선택한 Secret·승인·회전 이벤트를 서명 Webhook으로 전달하고 결과를 추적합니다.', badge: '서명 Webhook 제공', notice: 'v0.2.0은 HMAC-SHA256 Webhook 전송·이력·수동 재시도를 제공합니다. Kafka·Syslog·Mattermost sink, 독립 Event stream과 예약형 자동 재시도는 아직 지원하지 않습니다.', metrics: [{ label: '지원 이벤트', value: '8', detail: '관리자 선택' }, { label: '전달 방식', value: 'Webhook', detail: 'HMAC-SHA256' }, { label: '재시도', value: '수동', detail: '이력 API 제공' }], capabilities: ['Secret·승인·회전 이벤트', 'Secret 평문을 제외한 서명 payload', '전송 이력과 관리자 수동 재시도'], next: ['예약형 backoff 재시도', 'Kafka·Syslog sink', 'Mattermost 알림'], action: { label: 'Webhook 설정', path: '/admin/settings' } },
  'security-events': { eyebrow: 'Security detection', title: '보안 이벤트', description: '실패한 로그인, 권한 거부와 고위험 작업을 집중 검토하는 후속 탐지 화면입니다.', badge: '로드맵', notice: 'v0.2.0은 HTTP 결과를 감사 로그로 남깁니다. 별도 Incident 상태, 이상 탐지와 자동 Token 폐기는 지원하지 않습니다.', metrics: [{ label: '열림', value: '—', detail: 'Incident 엔진 미지원' }, { label: '심각', value: '—', detail: '탐지 엔진 미지원' }, { label: '닫힘', value: '—', detail: 'Incident 엔진 미지원' }], capabilities: ['인증 실패 감사 기록', '권한 거부 상태 기록', '키 API 요청 감사 기록'], next: ['접근량 이상 탐지', '자동 Token revoke', 'Incident timeline'], action: { label: '감사 로그', path: '/audit' } },
  cluster: { eyebrow: 'Infrastructure', title: '클러스터', description: '현재 노드 상태와 서비스 준비 상태를 확인합니다.', badge: '단일 노드', notice: 'v0.2.0은 PostgreSQL을 사용하는 단일 서비스 노드 배포 프로파일입니다. Raft·leader election·standby는 후속 범위입니다.', metrics: [{ label: '서비스 노드', value: '1', detail: '고정 8080 포트' }, { label: '상태', value: 'Ready', detail: '/readyz 확인' }, { label: '모드', value: 'Single', detail: 'PostgreSQL 외부 저장소' }], capabilities: ['Liveness·readiness', '무상태 웹/API 노드', 'PostgreSQL 상태 확인'], next: ['다중 노드 검증', 'Leader coordination', '읽기 확장'] },
  storage: { eyebrow: 'Encrypted storage', title: '스토리지', description: 'PostgreSQL 연결, 마이그레이션과 저장 암호화 상태를 확인합니다.', badge: 'PostgreSQL', metrics: [{ label: 'Backend', value: 'Postgres', detail: '필수 DSN' }, { label: '암호화', value: 'AES-GCM', detail: '평문 저장 금지' }, { label: 'Migration', value: '자동', detail: '기동 시 적용' }], capabilities: ['트랜잭션 기반 메타데이터', 'AES-256-GCM 민감 필드', '자동 schema migration'], next: ['PITR 운영 가이드', '암호화 백업 검증', 'Raft backend'] },
  'infrastructure-security': { eyebrow: 'Seal and recovery', title: 'Seal·백업', description: 'Root 암호화 키 경계와 PostgreSQL 백업·복구 절차를 관리합니다.', badge: '운영 가이드', notice: 'ENCRYPTION_KEY를 잃으면 암호화 데이터를 복구할 수 없습니다. 키는 이미지·DB 백업과 분리해 안전하게 보관하세요.', metrics: [{ label: 'Seal', value: 'Local KEK', detail: '환경변수 주입' }, { label: 'Backup', value: 'DB 외부', detail: 'PostgreSQL 운영 정책' }, { label: '복구 테스트', value: '필수', detail: '분기별 권장' }], capabilities: ['기동 시 키 검증', '설정·시크릿 암호화', '복구 절차 문서'], next: ['Shamir unseal', 'KMS·HSM auto-unseal', 'DR simulation'] },
  namespaces: { eyebrow: 'Tenant boundary', title: 'Namespace', description: '조직과 프로젝트 단위로 데이터·정책·감사 경계를 분리합니다.', badge: '로드맵', metrics: [{ label: '현재 Namespace', value: 'root', detail: '기본 조직' }, { label: '프로젝트', value: '0', detail: '하위 경계' }, { label: '분리 정책', value: 'RBAC', detail: '현재 역할 기반' }], capabilities: ['Namespace 헤더 수용 설계', '리소스 메타데이터', '관리자 역할 분리'], next: ['계층형 Namespace', 'Tenant별 auth mount', 'Quota·감사 격리'] },
  preferences: { eyebrow: 'Personalization', title: '화면 설정', description: '개인별 표시 밀도, 테마와 기본 시작 화면을 관리합니다.', badge: '로컬 설정', metrics: [{ label: '언어', value: '한국어', detail: '기본 UI' }, { label: '글꼴', value: '17px', detail: '데스크톱 기준' }, { label: '메뉴 상태', value: 'URL', detail: '새로 고침 복원' }], capabilities: ['한국어 기본 UI', 'OS 다크 모드 대응 기반', '브라우저 route 복원'], next: ['개인 Dashboard widget', 'Saved view', '밀도 설정'] },
  guide: { eyebrow: 'Help center', title: '빠른 사용 가이드', description: '시크릿을 등록하고 키·권한을 운영하는 핵심 흐름입니다.', badge: 'v0.2.0', metrics: [{ label: '1', value: '앱 등록', detail: 'Owner·환경 지정' }, { label: '2', value: '시크릿', detail: '암호화 저장' }, { label: '3', value: '정책 연결', detail: '최소 권한' }], capabilities: ['사용자 가이드: 저장소 docs/guides/user-guide.md', '관리자 가이드: 저장소 docs/guides/admin-guide.md', 'API 가이드: 저장소 docs/guides/api-guide.md'], next: ['오프라인 설치 후 관리자 로그인', 'Keycloak 연결 테스트', '승인 설정 확인'], action: { label: '시크릿 시작', path: '/secrets/new' } },
};

export function FeaturePage({ feature }: { feature: FeatureKey }) {
  const config = configs[feature];
  const navigate = useNavigate();
  return <>
    <PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description} actions={<Badge variant="light" color={config.badge.includes('로드맵') ? 'gray' : 'teal'} size="lg">{config.badge}</Badge>} />
    {config.notice && <Alert mb="lg" color="blue" icon={<Info size={20} />}>{config.notice}</Alert>}
    <SimpleGrid cols={{ base: 1, sm: 3 }} spacing="lg" mb="lg">{config.metrics.map((metric, index) => <Card key={metric.label} className="surface metric-card" radius="lg" p="lg"><Group justify="space-between"><ThemeIcon size={42} variant="light" color={index === 1 ? 'blue' : index === 2 ? 'orange' : 'teal'}>{index === 0 ? <ShieldCheck size={21} /> : index === 1 ? <Activity size={21} /> : <Clock3 size={21} />}</ThemeIcon><Text fz={25} fw={850}>{metric.value}</Text></Group><Text fw={750} mt="md">{metric.label}</Text><Text size="sm" c="dimmed">{metric.detail}</Text></Card>)}</SimpleGrid>
    <Grid gutter="lg"><Grid.Col span={{ base: 12, md: 7 }}><Card className="surface" radius="lg" p="xl"><Group mb="lg"><ThemeIcon color="teal" variant="light" size={42}><CheckCircle2 size={21} /></ThemeIcon><div><Title order={2} fz="lg">구현·설계 범위</Title><Text size="sm" c="dimmed">실제 지원 여부는 상단 배지와 안내를 우선합니다.</Text></div></Group><List spacing="md" icon={<ThemeIcon color="teal" size={24} radius="xl"><CheckCircle2 size={14} /></ThemeIcon>}>{config.capabilities.map((item) => <List.Item key={item}>{item}</List.Item>)}</List>{config.action && <Button mt="xl" variant="light" rightSection={<ArrowRight size={17} />} onClick={() => navigate(config.action!.path)}>{config.action.label}</Button>}</Card></Grid.Col><Grid.Col span={{ base: 12, md: 5 }}><Card className="surface" radius="lg" p="xl"><Group mb="lg"><ThemeIcon color="gray" variant="light" size={42}><Wrench size={21} /></ThemeIcon><div><Title order={2} fz="lg">확장 계획</Title><Text size="sm" c="dimmed">호환 계약과 분리된 후속 기능</Text></div></Group><Timeline active={-1} bulletSize={26}>{config.next.map((item) => <Timeline.Item key={item} bullet={<CircleDashed size={14} />} title={item}><Text size="sm" c="dimmed">검증 후 순차 제공</Text></Timeline.Item>)}</Timeline></Card></Grid.Col></Grid>
  </>;
}
